// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

//`timescale 1 ns / 1 ps 

module Avg_Cent_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ImgRef_dout,
        ImgRef_empty_n,
        ImgRef_read,
        icentroid_address0,
        icentroid_ce0,
        icentroid_we0,
        icentroid_d0,
        icentroid_address1,
        icentroid_ce1,
        icentroid_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] ImgRef_dout;
input   ImgRef_empty_n;
output   ImgRef_read;
output  [7:0] icentroid_address0;
output   icentroid_ce0;
output   icentroid_we0;
output  [31:0] icentroid_d0;
output  [7:0] icentroid_address1;
output   icentroid_ce1;
input  [31:0] icentroid_q1;

reg ap_idle;
reg ImgRef_read;
reg icentroid_ce0;
reg icentroid_we0;
reg icentroid_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln19_fu_113_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ImgRef_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] select_ln19_1_fu_151_p3;
reg   [10:0] select_ln19_1_reg_275;
reg   [7:0] icentroid_addr_reg_281;
reg   [7:0] icentroid_addr_reg_281_pp0_iter2_reg;
wire   [63:0] zext_ln21_fu_159_p1;
reg   [7:0] itBand_fu_56;
wire   [7:0] add_ln37_fu_164_p2;
wire    ap_loop_init;
reg   [10:0] itPixel_fu_60;
reg   [17:0] indvar_flatten_fu_64;
wire   [17:0] add_ln19_fu_119_p2;
reg   [31:0] newPixel0_1_fu_68;
wire   [31:0] newPixel0_fu_227_p3;
wire   [0:0] icmp_ln21_fu_131_p2;
wire   [10:0] add_ln19_1_fu_145_p2;
wire   [7:0] select_ln19_fu_137_p3;
wire   [0:0] cmp7_i_fu_185_p2;
wire   [31:0] prev0_fu_195_p3;
wire   [31:0] zext_ln34_fu_203_p1;
wire   [31:0] add_ln34_fu_207_p2;
wire   [21:0] lshr_ln_fu_213_p4;
wire   [0:0] cmp10_i_fu_190_p2;
wire   [31:0] zext_ln34_1_fu_223_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 itBand_fu_56 = 8'd0;
#0 itPixel_fu_60 = 11'd0;
#0 indvar_flatten_fu_64 = 18'd0;
#0 newPixel0_1_fu_68 = 32'd0;
#0 ap_done_reg = 1'b0;
end

Avg_Cent_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_64 <= 18'd0;
        end else if (((icmp_ln19_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_64 <= add_ln19_fu_119_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            itBand_fu_56 <= 8'd0;
        end else if (((icmp_ln19_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            itBand_fu_56 <= add_ln37_fu_164_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            itPixel_fu_60 <= 11'd0;
        end else if (((icmp_ln19_fu_113_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            itPixel_fu_60 <= select_ln19_1_fu_151_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icentroid_addr_reg_281 <= zext_ln21_fu_159_p1;
        select_ln19_1_reg_275 <= select_ln19_1_fu_151_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icentroid_addr_reg_281_pp0_iter2_reg <= icentroid_addr_reg_281;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        newPixel0_1_fu_68 <= newPixel0_fu_227_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ImgRef_blk_n = ImgRef_empty_n;
    end else begin
        ImgRef_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ImgRef_read = 1'b1;
    end else begin
        ImgRef_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln19_fu_113_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        icentroid_ce0 = 1'b1;
    end else begin
        icentroid_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icentroid_ce1 = 1'b1;
    end else begin
        icentroid_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        icentroid_we0 = 1'b1;
    end else begin
        icentroid_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_145_p2 = (itPixel_fu_60 + 11'd1);

assign add_ln19_fu_119_p2 = (indvar_flatten_fu_64 + 18'd1);

assign add_ln34_fu_207_p2 = (prev0_fu_195_p3 + zext_ln34_fu_203_p1);

assign add_ln37_fu_164_p2 = (select_ln19_fu_137_p3 + 8'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (1'b0 == ImgRef_empty_n);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign cmp10_i_fu_190_p2 = ((select_ln19_1_reg_275 == 11'd1023) ? 1'b1 : 1'b0);

assign cmp7_i_fu_185_p2 = ((select_ln19_1_reg_275 == 11'd0) ? 1'b1 : 1'b0);

assign icentroid_address0 = icentroid_addr_reg_281_pp0_iter2_reg;

assign icentroid_address1 = zext_ln21_fu_159_p1;

assign icentroid_d0 = newPixel0_1_fu_68;

assign icmp_ln19_fu_113_p2 = ((indvar_flatten_fu_64 == 18'd163840) ? 1'b1 : 1'b0);

assign icmp_ln21_fu_131_p2 = ((itBand_fu_56 == 8'd160) ? 1'b1 : 1'b0);

assign lshr_ln_fu_213_p4 = {{add_ln34_fu_207_p2[31:10]}};

assign newPixel0_fu_227_p3 = ((cmp10_i_fu_190_p2[0:0] == 1'b1) ? zext_ln34_1_fu_223_p1 : add_ln34_fu_207_p2);

assign prev0_fu_195_p3 = ((cmp7_i_fu_185_p2[0:0] == 1'b1) ? 32'd0 : icentroid_q1);

assign select_ln19_1_fu_151_p3 = ((icmp_ln21_fu_131_p2[0:0] == 1'b1) ? add_ln19_1_fu_145_p2 : itPixel_fu_60);

assign select_ln19_fu_137_p3 = ((icmp_ln21_fu_131_p2[0:0] == 1'b1) ? 8'd0 : itBand_fu_56);

assign zext_ln21_fu_159_p1 = select_ln19_fu_137_p3;

assign zext_ln34_1_fu_223_p1 = lshr_ln_fu_213_p4;

assign zext_ln34_fu_203_p1 = ImgRef_dout;

endmodule //Avg_Cent_Avg_Cent_Pipeline_sum_p_loop_sum_b_loop
